#!/bin/bash
# Script Generator for Runnables
# Generates start scripts for cloud-sync and vm-sync

set -e

# Check if scripts directory is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 <scripts_directory>"
    exit 1
fi

SCRIPTS_DIR="$1"

# Create scripts directory if it doesn't exist
mkdir -p "$SCRIPTS_DIR"

echo "📜 Generating start scripts in $SCRIPTS_DIR..."

# Generate cloud-sync start script
cat > "$SCRIPTS_DIR/start-cloud-sync.sh" << 'EOF'
#!/bin/bash
# Cloud-Sync Start Script
# Auto-generated by Makefile

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BINARY_DIR="$(dirname "$SCRIPT_DIR")"
BINARY="$BINARY_DIR/cloud-sync"
CONFIG="$BINARY_DIR/configs/cloud-example.yaml"

echo -e "${BLUE}🚀 Starting Cloud-Sync Service${NC}"
echo -e "Binary: $BINARY"
echo -e "Config: $CONFIG"

# Check if binary exists
if [ ! -f "$BINARY" ]; then
    echo -e "${RED}❌ Binary not found: $BINARY${NC}"
    echo -e "${YELLOW}Run 'make runnables' to build binaries${NC}"
    exit 1
fi

# Check if config exists
if [ ! -f "$CONFIG" ]; then
    echo -e "${RED}❌ Config not found: $CONFIG${NC}"
    echo -e "${YELLOW}Run 'make runnables' to generate configs${NC}"
    exit 1
fi

# Start cloud-sync with required -config flag (per memory requirement)
echo -e "${BLUE}🎯 Starting cloud-sync with OAuth2 authentication...${NC}"
exec "$BINARY" -config "$CONFIG"
EOF

# Generate vm-sync start script
cat > "$SCRIPTS_DIR/start-vm-sync.sh" << 'EOF'
#!/bin/bash
# VM-Sync Start Script
# Auto-generated by Makefile

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BINARY_DIR="$(dirname "$SCRIPT_DIR")"
BINARY="$BINARY_DIR/vm-sync"
CONFIG="$BINARY_DIR/configs/vm-example.yaml"

echo -e "${BLUE}🚀 Starting VM-Sync Service${NC}"
echo -e "Binary: $BINARY"
echo -e "Config: $CONFIG"

# Check if binary exists
if [ ! -f "$BINARY" ]; then
    echo -e "${RED}❌ Binary not found: $BINARY${NC}"
    echo -e "${YELLOW}Run 'make runnables' to build binaries${NC}"
    exit 1
fi

# Check if config exists
if [ ! -f "$CONFIG" ]; then
    echo -e "${RED}❌ Config not found: $CONFIG${NC}"
    echo -e "${YELLOW}Run 'make runnables' to generate configs${NC}"
    exit 1
fi

# Check if cloud-sync is reachable
CLOUD_URL="http://localhost:8080"
echo -e "${YELLOW}🔍 Checking cloud-sync connectivity...${NC}"
if curl -s --max-time 5 "$CLOUD_URL/health" > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Cloud-sync is reachable at $CLOUD_URL${NC}"
else
    echo -e "${YELLOW}⚠️  Cloud-sync not reachable at $CLOUD_URL${NC}"
    echo -e "${YELLOW}   Make sure cloud-sync is running first${NC}"
fi

# Start vm-sync with HTTP telemetry (no WebSocket dependency for telemetry)
echo -e "${BLUE}🎯 Starting vm-sync with HTTP telemetry...${NC}"
exec "$BINARY" -config "$CONFIG"
EOF

# Generate deployment helper script
cat > "$SCRIPTS_DIR/deploy.sh" << 'EOF'
#!/bin/bash
# Deployment Helper Script
# Auto-generated by Makefile

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo -e "${BLUE}🚀 Go Data Sync Deployment Helper${NC}"
echo -e ""

# Function to start cloud-sync in background
start_cloud_sync() {
    echo -e "${YELLOW}Starting cloud-sync in background...${NC}"
    nohup "$SCRIPT_DIR/start-cloud-sync.sh" > cloud-sync.log 2>&1 &
    CLOUD_PID=$!
    echo $CLOUD_PID > cloud-sync.pid
    echo -e "${GREEN}✅ Cloud-sync started (PID: $CLOUD_PID)${NC}"
    echo -e "Log: cloud-sync.log"
}

# Function to start vm-sync in background
start_vm_sync() {
    echo -e "${YELLOW}Starting vm-sync in background...${NC}"
    sleep 5  # Wait for cloud-sync to be ready
    nohup "$SCRIPT_DIR/start-vm-sync.sh" > vm-sync.log 2>&1 &
    VM_PID=$!
    echo $VM_PID > vm-sync.pid
    echo -e "${GREEN}✅ VM-sync started (PID: $VM_PID)${NC}"
    echo -e "Log: vm-sync.log"
}

# Function to stop services
stop_services() {
    echo -e "${YELLOW}Stopping services...${NC}"
    
    if [ -f vm-sync.pid ]; then
        VM_PID=$(cat vm-sync.pid)
        if kill -0 $VM_PID 2>/dev/null; then
            kill $VM_PID
            echo -e "${GREEN}✅ VM-sync stopped${NC}"
        fi
        rm -f vm-sync.pid
    fi
    
    if [ -f cloud-sync.pid ]; then
        CLOUD_PID=$(cat cloud-sync.pid)
        if kill -0 $CLOUD_PID 2>/dev/null; then
            kill $CLOUD_PID
            echo -e "${GREEN}✅ Cloud-sync stopped${NC}"
        fi
        rm -f cloud-sync.pid
    fi
}

# Function to show status
show_status() {
    echo -e "${BLUE}📊 Service Status${NC}"
    
    if [ -f cloud-sync.pid ]; then
        CLOUD_PID=$(cat cloud-sync.pid)
        if kill -0 $CLOUD_PID 2>/dev/null; then
            echo -e "${GREEN}✅ Cloud-sync running (PID: $CLOUD_PID)${NC}"
        else
            echo -e "${RED}❌ Cloud-sync not running${NC}"
        fi
    else
        echo -e "${RED}❌ Cloud-sync not started${NC}"
    fi
    
    if [ -f vm-sync.pid ]; then
        VM_PID=$(cat vm-sync.pid)
        if kill -0 $VM_PID 2>/dev/null; then
            echo -e "${GREEN}✅ VM-sync running (PID: $VM_PID)${NC}"
        else
            echo -e "${RED}❌ VM-sync not running${NC}"
        fi
    else
        echo -e "${RED}❌ VM-sync not started${NC}"
    fi
}

# Main menu
case "${1:-help}" in
    start)
        stop_services  # Clean stop first
        start_cloud_sync
        start_vm_sync
        echo -e ""
        echo -e "${GREEN}🎉 All services started successfully!${NC}"
        echo -e "Cloud-sync: http://localhost:8080/dashboard"
        echo -e "VM-sync: http://localhost:8081/health"
        ;;
    stop)
        stop_services
        ;;
    status)
        show_status
        ;;
    restart)
        stop_services
        sleep 2
        start_cloud_sync
        start_vm_sync
        ;;
    logs)
        echo -e "${BLUE}📋 Service Logs${NC}"
        echo -e "${YELLOW}Cloud-sync log:${NC}"
        tail -n 20 cloud-sync.log 2>/dev/null || echo "No cloud-sync log found"
        echo -e ""
        echo -e "${YELLOW}VM-sync log:${NC}"
        tail -n 20 vm-sync.log 2>/dev/null || echo "No vm-sync log found"
        ;;
    *)
        echo -e "Usage: $0 {start|stop|status|restart|logs}"
        echo -e ""
        echo -e "Commands:"
        echo -e "  start    Start all services"
        echo -e "  stop     Stop all services"
        echo -e "  status   Show service status"
        echo -e "  restart  Restart all services"
        echo -e "  logs     Show recent logs"
        ;;
esac
EOF

# Make all scripts executable
chmod +x "$SCRIPTS_DIR"/*.sh

echo "✅ Generated start scripts:"
echo "  $SCRIPTS_DIR/start-cloud-sync.sh"
echo "  $SCRIPTS_DIR/start-vm-sync.sh"
echo "  $SCRIPTS_DIR/deploy.sh"